export const SHIPPING_RATE_CNY_PER_KG = 80;

export type CostConfidence = 'confirmed' | 'estimated' | 'needs_review';

export const INVENTORY_COSTING_MEMORY = [
  'One uploaded image is one inventory cost record and maps to one website catalog style.',
  'Do not aggregate or weight-average multiple images together, even when they look like the same style.',
  'If two images look like the same style, analyze and store their sizes separately.',
  'Parse labels like N*P as N purchased strands/items at P CNY per strand/item.',
  'Freight from China to the UK is 80 CNY/kg.',
  'Freight per strand = estimatedWeightGPerStrand / 1000 * 80.',
  'Total cost per strand = unitPurchasePriceCny + shippingCnyPerStrand.',
  'Unit cost per bead = totalCostCnyPerStrand / beadsPerStrand.',
  'When exact weight/count is unavailable, store an estimate and mark confidence for later review.',
];

export interface InventoryCostLotInput {
  id: string;
  catalogSlug: string;
  catalogName: string;
  sourceImageFile: string;
  labelText: string;
  productName: string;
  material: string;
  shape: string;
  sizeMm?: number;
  purchaseQuantity: number;
  unitPurchasePriceCny: number;
  beadsPerStrand: number;
  estimatedWeightGPerStrand: number;
  priceConfidence: CostConfidence;
  countConfidence: CostConfidence;
  weightConfidence: CostConfidence;
  notes?: string;
}

export interface InventoryCostLot extends InventoryCostLotInput {
  shippingCnyPerStrand: number;
  totalCostCnyPerStrand: number;
  unitCostCnyPerBead: number;
  totalPurchasePriceCny: number;
  totalShippingCny: number;
  totalLandedCostCny: number;
  totalBeads: number;
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

function sphereWeightG(sizeMm: number, densityGPerCm3: number, shapeFactor = 1): number {
  const radiusMm = sizeMm / 2;
  const volumeCm3 = (4 / 3) * Math.PI * radiusMm ** 3 / 1000;
  return volumeCm3 * densityGPerCm3 * shapeFactor;
}

const obsidianDensity = 2.4;
const quartzDensity = 2.65;
const howliteDensity = 2.53;
const tigerEyeDensity = 2.64;

export const inventoryCostLotInputs: InventoryCostLotInput[] = [
  {
    id: 'silver-sheen-obsidian-cat-mix-45',
    catalogSlug: 'silver-sheen-obsidian-cat',
    catalogName: 'Silver Sheen Obsidian Cat',
    sourceImageFile: 'IMG_6445.jpeg',
    labelText: '1*45 银曜石',
    productName: '银曜石猫猫混圆珠手串',
    material: '银曜石',
    shape: 'carved cat + round spacer',
    sizeMm: 13.6,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 45,
    beadsPerStrand: 18,
    estimatedWeightGPerStrand: 25,
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '图片识别为网站里的银曜石猫猫款；按这一张图片对应的整串数量计算。',
  },
  {
    id: 'black-jade-square-45',
    catalogSlug: 'silver-sheen-obsidian-square',
    catalogName: 'Silver Sheen Obsidian Square',
    sourceImageFile: 'IMG_6442.jpeg',
    labelText: '1*45 墨翠方块',
    productName: '墨翠方块珠',
    material: '墨翠',
    shape: 'square',
    sizeMm: 10,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 45,
    beadsPerStrand: 10,
    estimatedWeightGPerStrand: 28,
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '图片识别为网站里的黑色方块珠款；标签写墨翠方块，先匹配到已上传的方块珠。',
  },
  {
    id: 'silver-sheen-obsidian-round-8mm-18',
    catalogSlug: 'silver-sheen-obsidian-round',
    catalogName: 'Silver Sheen Obsidian Round',
    sourceImageFile: 'IMG_6437.jpeg',
    labelText: '1*18 银曜石',
    productName: '银曜石圆珠',
    material: '银曜石',
    shape: 'round',
    sizeMm: 8,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 18,
    beadsPerStrand: 24,
    estimatedWeightGPerStrand: round2(sphereWeightG(8, obsidianDensity) * 24),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
  },
  {
    id: 'silver-sheen-obsidian-round-8mm-20',
    catalogSlug: 'silver-sheen-obsidian-round',
    catalogName: 'Silver Sheen Obsidian Round',
    sourceImageFile: 'IMG_6433.jpeg',
    labelText: '1*20 银曜石',
    productName: '银曜石圆珠',
    material: '银曜石',
    shape: 'round',
    sizeMm: 8,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 20,
    beadsPerStrand: 24,
    estimatedWeightGPerStrand: round2(sphereWeightG(8, obsidianDensity) * 24),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
  },
  {
    id: 'silver-sheen-obsidian-round-12mm-25',
    catalogSlug: 'silver-sheen-obsidian-round',
    catalogName: 'Silver Sheen Obsidian Round',
    sourceImageFile: 'IMG_6427.jpeg',
    labelText: '1*25 曜石',
    productName: '银曜石圆珠',
    material: '银曜石',
    shape: 'round',
    sizeMm: 12,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 25,
    beadsPerStrand: 20,
    estimatedWeightGPerStrand: round2(sphereWeightG(12, obsidianDensity) * 20),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
  },
  {
    id: 'silver-sheen-obsidian-round-small-28',
    catalogSlug: 'silver-sheen-obsidian-round',
    catalogName: 'Silver Sheen Obsidian Round',
    sourceImageFile: 'IMG_6416.jpeg',
    labelText: '3*28 银曜石',
    productName: '银曜石小圆珠',
    material: '银曜石',
    shape: 'round',
    sizeMm: 6,
    purchaseQuantity: 3,
    unitPurchasePriceCny: 28,
    beadsPerStrand: 33,
    estimatedWeightGPerStrand: round2(sphereWeightG(6, obsidianDensity) * 33),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '标签为 3 串，每串按 28 元记录。',
  },
  {
    id: 'silver-sheen-obsidian-faceted-10mm-15',
    catalogSlug: 'silver-sheen-obsidian',
    catalogName: 'Silver Sheen Obsidian',
    sourceImageFile: 'IMG_6405.jpeg',
    labelText: '1*15 银曜石',
    productName: '银曜石切面珠',
    material: '银曜石',
    shape: 'faceted round',
    sizeMm: 10,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 15,
    beadsPerStrand: 18,
    estimatedWeightGPerStrand: round2(sphereWeightG(10, obsidianDensity, 0.85) * 18),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
  },
  {
    id: 'silver-sheen-obsidian-faceted-10mm-28',
    catalogSlug: 'silver-sheen-obsidian',
    catalogName: 'Silver Sheen Obsidian',
    sourceImageFile: 'IMG_6399.jpeg',
    labelText: '1*28 银曜石',
    productName: '银曜石切面珠',
    material: '银曜石',
    shape: 'faceted round',
    sizeMm: 10,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 28,
    beadsPerStrand: 20,
    estimatedWeightGPerStrand: round2(sphereWeightG(10, obsidianDensity, 0.85) * 20),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
  },
  {
    id: 'silver-sheen-obsidian-faceted-7mm-25',
    catalogSlug: 'silver-sheen-obsidian',
    catalogName: 'Silver Sheen Obsidian',
    sourceImageFile: 'IMG_6392.jpeg',
    labelText: '3*25 银曜石',
    productName: '银曜石切面珠',
    material: '银曜石',
    shape: 'faceted round',
    sizeMm: 7,
    purchaseQuantity: 3,
    unitPurchasePriceCny: 25,
    beadsPerStrand: 20,
    estimatedWeightGPerStrand: round2(sphereWeightG(7, obsidianDensity, 0.85) * 20),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '标签为 3 串，每串按 25 元记录。',
  },
  {
    id: 'silver-sheen-obsidian-faceted-7mm-22',
    catalogSlug: 'silver-sheen-obsidian',
    catalogName: 'Silver Sheen Obsidian',
    sourceImageFile: 'IMG_6391.jpeg',
    labelText: '2*22 银曜石',
    productName: '银曜石切面珠',
    material: '银曜石',
    shape: 'faceted round',
    sizeMm: 7,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 22,
    beadsPerStrand: 20,
    estimatedWeightGPerStrand: round2(sphereWeightG(7, obsidianDensity, 0.85) * 20),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '标签为 2 串，每串按 22 元记录。',
  },
  {
    id: 'silver-sheen-obsidian-heart-68',
    catalogSlug: 'silver-sheen-obsidian-heart',
    catalogName: 'Silver Sheen Obsidian Heart',
    sourceImageFile: 'IMG_6376.jpeg',
    labelText: '1*68 银曜石',
    productName: '银曜石爱心珠',
    material: '银曜石',
    shape: 'heart',
    sizeMm: 14,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 68,
    beadsPerStrand: 18,
    estimatedWeightGPerStrand: 49,
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '爱心珠体积按扁平异形估算；实际称重后建议覆盖。',
  },
  {
    id: 'tigers-eye-round-8-5mm-22',
    catalogSlug: 'tigers-eye',
    catalogName: "Tiger's Eye",
    sourceImageFile: 'IMG_6517.jpeg',
    labelText: '黄虎眼 8.5mm 价格 22 23粒',
    productName: '黄虎眼圆珠',
    material: '黄虎眼',
    shape: 'round',
    sizeMm: 8.5,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 22,
    beadsPerStrand: 23,
    estimatedWeightGPerStrand: round2(sphereWeightG(8.5, tigerEyeDensity) * 23),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 8.5mm、价格 22、23粒；纯采购价约 0.96 CNY/颗，含估算国际运费约 1.02 CNY/颗。',
  },
  {
    id: 'tigers-eye-round-10-5mm-18',
    catalogSlug: 'tigers-eye',
    catalogName: "Tiger's Eye",
    sourceImageFile: 'IMG_6524.jpeg',
    labelText: '黄虎眼 10.4mm 价格 18 19粒',
    productName: '黄虎眼圆珠',
    material: '黄虎眼',
    shape: 'round',
    sizeMm: 10.5,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 18,
    beadsPerStrand: 19,
    estimatedWeightGPerStrand: round2(sphereWeightG(10.5, tigerEyeDensity) * 19),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签照片写 10.4mm、价格 18、19粒；按用户指定 10.5mm 入库。纯采购价约 0.95 CNY/颗，含估算国际运费约 1.08 CNY/颗。',
  },
  {
    id: 'tigers-eye-round-6p5mm-30',
    catalogSlug: 'tigers-eye',
    catalogName: "Tiger's Eye",
    sourceImageFile: 'IMG_6513.jpeg',
    labelText: '30×4 黄虎眼 6.6mm 82粒',
    productName: '黄虎眼圆珠',
    material: '黄虎眼',
    shape: 'round',
    sizeMm: 6.5,
    purchaseQuantity: 4,
    unitPurchasePriceCny: 30,
    beadsPerStrand: 82,
    estimatedWeightGPerStrand: round2(sphereWeightG(6.5, tigerEyeDensity) * 82),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 6.6mm，网站按 6.5mm 上架；采购价约 0.37 CNY/颗，含估算国际运费约 0.40 CNY/颗。',
  },
  {
    id: 'red-tigers-eye-round-6p5mm-30',
    catalogSlug: 'red-tigers-eye',
    catalogName: "Red Tiger's Eye",
    sourceImageFile: 'IMG_6529.jpeg',
    labelText: '红虎眼 6.4mm 价格 30 86粒',
    productName: '红虎眼圆珠',
    material: '红虎眼',
    shape: 'round',
    sizeMm: 6.5,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 30,
    beadsPerStrand: 86,
    estimatedWeightGPerStrand: round2(sphereWeightG(6.5, tigerEyeDensity) * 86),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签照片写 6.4mm、价格 30、86粒；按用户指定 6.5mm 入库。纯采购价约 0.35 CNY/颗，含估算国际运费约 0.38 CNY/颗。',
  },
  {
    id: 'blue-tigers-eye-premium-round-12mm-35',
    catalogSlug: 'blue-tigers-eye-premium',
    catalogName: "Blue Tiger's Eye Premium",
    sourceImageFile: 'IMG_6630.jpeg',
    labelText: '12mm 3*35 蓝虎眼',
    productName: '高等级蓝虎眼圆珠',
    material: '蓝虎眼',
    shape: 'round',
    sizeMm: 12,
    purchaseQuantity: 3,
    unitPurchasePriceCny: 35,
    beadsPerStrand: 18,
    estimatedWeightGPerStrand: round2(sphereWeightG(12, tigerEyeDensity) * 18),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '标签可见 +12mm、价格 3*35 蓝虎眼；按每串 35 元、3 串记录。单串按 18 颗估算，含国际运费后约 2.14 CNY/颗。',
  },
  {
    id: 'lychee-jelly-round-12mm-25',
    catalogSlug: 'lychee-jelly',
    catalogName: 'Lychee Jelly',
    sourceImageFile: 'IMG_6656.jpeg',
    labelText: '荔枝冻玛瑙 12.3mm 25*2 17粒',
    productName: '荔枝冻玛瑙圆珠',
    material: '荔枝冻玛瑙',
    shape: 'round',
    sizeMm: 12.3,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 25,
    beadsPerStrand: 17,
    estimatedWeightGPerStrand: round2(sphereWeightG(12.3, quartzDensity) * 17),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 12.3mm、25*2、17粒；网站按 12mm 上架。纯采购价约 1.47 CNY/颗，含估算国际运费约 1.68 CNY/颗。',
  },
  {
    id: 'lychee-jelly-round-10mm-18',
    catalogSlug: 'lychee-jelly',
    catalogName: 'Lychee Jelly',
    sourceImageFile: 'IMG_6651.jpeg',
    labelText: '荔枝冻玛瑙 10mm 5*18 19粒',
    productName: '荔枝冻玛瑙圆珠',
    material: '荔枝冻玛瑙',
    shape: 'round',
    sizeMm: 10,
    purchaseQuantity: 5,
    unitPurchasePriceCny: 18,
    beadsPerStrand: 19,
    estimatedWeightGPerStrand: round2(sphereWeightG(10, quartzDensity) * 19),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 10mm、5*18、19粒；纯采购价约 0.95 CNY/颗，含估算国际运费约 1.06 CNY/颗。',
  },
  {
    id: 'lychee-jelly-round-8mm-20',
    catalogSlug: 'lychee-jelly',
    catalogName: 'Lychee Jelly',
    sourceImageFile: 'IMG_6650.jpeg',
    labelText: '荔枝冻玛瑙 8mm 2*20 23粒',
    productName: '荔枝冻玛瑙圆珠',
    material: '荔枝冻玛瑙',
    shape: 'round',
    sizeMm: 8,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 20,
    beadsPerStrand: 23,
    estimatedWeightGPerStrand: round2(sphereWeightG(8, quartzDensity) * 23),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 8mm、2*20、23粒；纯采购价约 0.87 CNY/颗，含估算国际运费约 0.93 CNY/颗。',
  },
  {
    id: 'lychee-jelly-round-6mm-25',
    catalogSlug: 'lychee-jelly',
    catalogName: 'Lychee Jelly',
    sourceImageFile: 'IMG_6640.jpeg',
    labelText: '荔枝冻玛瑙 6.3mm 3*25 85粒',
    productName: '荔枝冻玛瑙圆珠',
    material: '荔枝冻玛瑙',
    shape: 'round',
    sizeMm: 6.3,
    purchaseQuantity: 3,
    unitPurchasePriceCny: 25,
    beadsPerStrand: 85,
    estimatedWeightGPerStrand: round2(sphereWeightG(6.3, quartzDensity) * 85),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 6.3mm、3*25、85粒；网站按 6mm 上架。纯采购价约 0.29 CNY/颗，含估算国际运费约 0.32 CNY/颗。',
  },
  {
    id: 'green-agate-round-10mm-20',
    catalogSlug: 'green-agate',
    catalogName: 'Green Agate',
    sourceImageFile: 'IMG_6675.jpeg',
    labelText: '绿玛瑙 10mm 价格 20 19粒',
    productName: '绿玛瑙圆珠',
    material: '绿玛瑙',
    shape: 'round',
    sizeMm: 10,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 20,
    beadsPerStrand: 19,
    estimatedWeightGPerStrand: round2(sphereWeightG(10, quartzDensity) * 19),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签可见 10mm、价格 20、19粒；纯采购价约 1.05 CNY/颗，含估算国际运费约 1.17 CNY/颗。',
  },
  {
    id: 'green-agate-round-6p3mm-19',
    catalogSlug: 'green-agate',
    catalogName: 'Green Agate',
    sourceImageFile: 'IMG_6661.jpeg',
    labelText: '绿玛瑙 6.3mm 19*2 88粒',
    productName: '绿玛瑙圆珠',
    material: '绿玛瑙',
    shape: 'round',
    sizeMm: 6.3,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 19,
    beadsPerStrand: 88,
    estimatedWeightGPerStrand: round2(sphereWeightG(6.3, quartzDensity) * 88),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签可见 6.3mm、19*2、88粒；按每串 19 元、2 串记录。纯采购价约 0.22 CNY/颗，含估算国际运费约 0.25 CNY/颗。',
  },
  {
    id: 'blue-agate-round-11p7mm-28',
    catalogSlug: 'blue-agate',
    catalogName: 'Blue Agate',
    sourceImageFile: 'IMG_6626.jpeg',
    labelText: '蓝玛瑙 11.7mm / 12mm 3*28 17粒',
    productName: '蓝玛瑙圆珠',
    material: '蓝玛瑙',
    shape: 'round',
    sizeMm: 11.7,
    purchaseQuantity: 3,
    unitPurchasePriceCny: 28,
    beadsPerStrand: 17,
    estimatedWeightGPerStrand: round2(sphereWeightG(11.7, quartzDensity) * 17),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 11.7mm、12mm、3*28 蓝玛瑙、17粒；按每串 28 元、3 串记录。纯采购价约 1.65 CNY/颗，含估算国际运费约 1.82 CNY/颗。',
  },
  {
    id: 'blue-agate-round-10p2mm-15',
    catalogSlug: 'blue-agate',
    catalogName: 'Blue Agate',
    sourceImageFile: 'IMG_6614.jpeg',
    labelText: '蓝玛瑙 10.2mm 2*15 19粒',
    productName: '蓝玛瑙圆珠',
    material: '蓝玛瑙',
    shape: 'round',
    sizeMm: 10.2,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 15,
    beadsPerStrand: 19,
    estimatedWeightGPerStrand: round2(sphereWeightG(10.2, quartzDensity) * 19),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 10.2mm、2*15 蓝玛瑙、19粒；按每串 15 元、2 串记录。纯采购价约 0.79 CNY/颗，含估算国际运费约 0.91 CNY/颗。',
  },
  {
    id: 'blue-agate-round-6p3mm-22',
    catalogSlug: 'blue-agate',
    catalogName: 'Blue Agate',
    sourceImageFile: 'IMG_6603.jpeg',
    labelText: '蓝玛瑙 6.3mm 2*22 88粒',
    productName: '蓝玛瑙圆珠',
    material: '蓝玛瑙',
    shape: 'round',
    sizeMm: 6.3,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 22,
    beadsPerStrand: 88,
    estimatedWeightGPerStrand: round2(sphereWeightG(6.3, quartzDensity) * 88),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '标签写 6.3mm、2*22 蓝玛瑙、88粒；按每串 22 元、2 串记录。纯采购价约 0.25 CNY/颗，含估算国际运费约 0.28 CNY/颗。',
  },
  {
    id: 'ice-obsidian-round-10-5mm-18',
    catalogSlug: 'ice-obsidian',
    catalogName: 'Ice Obsidian',
    sourceImageFile: 'IMG_6567.HEIC',
    labelText: '冰曜石 10.5mm 价格 2*18',
    productName: '冰曜石圆珠',
    material: '冰曜石',
    shape: 'round',
    sizeMm: 10.5,
    purchaseQuantity: 2,
    unitPurchasePriceCny: 18,
    beadsPerStrand: 18,
    estimatedWeightGPerStrand: round2(sphereWeightG(10.5, obsidianDensity) * 18),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
    notes: '标签可见 10.5mm、2*18；按每串 18 元、2 串记录。图片可见单串约 18 颗，采购价约 1.00 CNY/颗，含估算国际运费约 1.12 CNY/颗。',
  },
  {
    id: 'gold-alphabet-18k-11x12mm-1p60',
    catalogSlug: 'gold-alphabet-a',
    catalogName: 'Alphabet',
    sourceImageFile: 'IMG_6563.jpeg',
    labelText: '304不锈钢 炉内真空电镀18K金 字母隔珠 11×12mm 约0.2g/个 成本1.60',
    productName: '18K金色字母隔珠连接件',
    material: '304不锈钢 / 炉内真空电镀18K金',
    shape: 'letter connector spacer with top loop and open jump ring',
    sizeMm: 12,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 1.6,
    beadsPerStrand: 1,
    estimatedWeightGPerStrand: 0.2,
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'confirmed',
    notes: 'A-Z 字母同款单个成本价 1.60 CNY；按 0.2g/个和 80 CNY/kg 运费估算，单个到岸成本约 1.62 CNY。规格为宽 11mm、高 12mm。',
  },
  {
    id: 'howlite-round-8mm-20',
    catalogSlug: 'howlite',
    catalogName: 'Howlite',
    sourceImageFile: 'IMG_6283.jpeg',
    labelText: '1*20 白松石',
    productName: '白松石圆珠',
    material: '白松石',
    shape: 'round',
    sizeMm: 8,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 20,
    beadsPerStrand: 23,
    estimatedWeightGPerStrand: round2(sphereWeightG(8, howliteDensity) * 23),
    priceConfidence: 'confirmed',
    countConfidence: 'estimated',
    weightConfidence: 'estimated',
  },
  {
    id: 'howlite-round-6-4mm-25',
    catalogSlug: 'howlite',
    catalogName: 'Howlite',
    sourceImageFile: 'IMG_6273.jpeg',
    labelText: '1*25 白松石',
    productName: '白松石小圆珠',
    material: '白松石',
    shape: 'round',
    sizeMm: 6.4,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 25,
    beadsPerStrand: 88,
    estimatedWeightGPerStrand: round2(sphereWeightG(6.4, howliteDensity) * 88),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '用户确认：25 CNY/条，每条 88 颗，规格 6.4mm。',
  },
  {
    id: 'clear-quartz-round-8mm-10',
    catalogSlug: 'clear-quartz',
    catalogName: 'Clear Quartz',
    sourceImageFile: 'IMG_6254.jpeg',
    labelText: '白水晶 8mm 24颗 ¥10',
    productName: '白水晶圆珠',
    material: '白水晶',
    shape: 'round',
    sizeMm: 8,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 10,
    beadsPerStrand: 24,
    estimatedWeightGPerStrand: round2(sphereWeightG(8, quartzDensity) * 24),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '用户确认：8mm，24 颗，总成本 10 CNY。',
  },
  {
    id: 'clear-quartz-round-10mm-12',
    catalogSlug: 'clear-quartz',
    catalogName: 'Clear Quartz',
    sourceImageFile: 'manual-entry-clear-quartz-10mm',
    labelText: '白水晶 10mm 19颗 ¥12',
    productName: '白水晶圆珠',
    material: '白水晶',
    shape: 'round',
    sizeMm: 10,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 12,
    beadsPerStrand: 19,
    estimatedWeightGPerStrand: round2(sphereWeightG(10, quartzDensity) * 19),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '用户确认：10mm，19 颗，总成本 12 CNY。',
  },
  {
    id: 'clear-quartz-round-9mm-8',
    catalogSlug: 'clear-quartz',
    catalogName: 'Clear Quartz',
    sourceImageFile: 'manual-entry-clear-quartz-9mm',
    labelText: '白水晶 9mm 21颗 ¥8',
    productName: '白水晶圆珠',
    material: '白水晶',
    shape: 'round',
    sizeMm: 9,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 8,
    beadsPerStrand: 21,
    estimatedWeightGPerStrand: round2(sphereWeightG(9, quartzDensity) * 21),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '用户确认：9mm，21 颗，总成本 8 CNY。',
  },
  {
    id: 'clear-quartz-round-12mm-22',
    catalogSlug: 'clear-quartz',
    catalogName: 'Clear Quartz',
    sourceImageFile: 'manual-entry-clear-quartz-12mm',
    labelText: '白水晶 12mm 16颗 ¥22',
    productName: '白水晶圆珠',
    material: '白水晶',
    shape: 'round',
    sizeMm: 12,
    purchaseQuantity: 1,
    unitPurchasePriceCny: 22,
    beadsPerStrand: 16,
    estimatedWeightGPerStrand: round2(sphereWeightG(12, quartzDensity) * 16),
    priceConfidence: 'confirmed',
    countConfidence: 'confirmed',
    weightConfidence: 'estimated',
    notes: '用户确认：12mm，16 颗，总成本 22 CNY。',
  },
];

export function calculateInventoryLot(input: InventoryCostLotInput): InventoryCostLot {
  const shippingCnyPerStrand = round2((input.estimatedWeightGPerStrand / 1000) * SHIPPING_RATE_CNY_PER_KG);
  const totalCostCnyPerStrand = round2(input.unitPurchasePriceCny + shippingCnyPerStrand);
  const unitCostCnyPerBead = round2(totalCostCnyPerStrand / input.beadsPerStrand);
  const totalPurchasePriceCny = round2(input.unitPurchasePriceCny * input.purchaseQuantity);
  const totalShippingCny = round2(shippingCnyPerStrand * input.purchaseQuantity);
  const totalLandedCostCny = round2(totalCostCnyPerStrand * input.purchaseQuantity);
  const totalBeads = input.beadsPerStrand * input.purchaseQuantity;

  return {
    ...input,
    shippingCnyPerStrand,
    totalCostCnyPerStrand,
    unitCostCnyPerBead,
    totalPurchasePriceCny,
    totalShippingCny,
    totalLandedCostCny,
    totalBeads,
  };
}

export const inventoryCostLots = inventoryCostLotInputs.map(calculateInventoryLot);
